# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Interlude"
license = "MIT"
licenselink = "https://github.com/samuelematias/interlude/blob/main/LICENSE"
description = "Theme to be used on websites built with Hugo. So, I use it on my braindump"
homepage = "https://braindump.samuelematias.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Samuel Matias"
  homepage = "https://www.samuelematias.com/"
